// Nested beer styles
export const beerStyles = [
  {
    category: 'Ale Styles',
    styles: [
      {
        name: 'British Origin Ale Styles',
        options: [
          'Ordinary Bitter',
          'Special Bitter or Best Bitter',
          'Extra Special Bitter',
          'Scottish-Style Light Ale',
          'Scottish-Style Heavy Ale',
          'Scottish-Style Export Ale',
          'English-Style Summer Ale',
          'Classic English-Style Pale Ale',
          'British-Style India Pale Ale',
          'Strong Ale',
          'Old Ale',
          'English-Style Pale Mild Ale',
          'English-Style Dark Mild Ale',
          'English-Style Brown Ale',
          'Brown Porter',
          'Robust Porter',
          'Sweet Stout or Cream Stout',
          'Oatmeal Stout',
          'Scotch Ale or Wee Heavy',
          'British-Style Imperial Stout',
          'British-Style Barley Wine Ale',
          'Wood- and Barrel-Aged Beer',
        ],
      },
      {
        name: 'Irish Origin Ale Styles',
        options: ['Irish-Style Red Ale', 'Classic Irish-Style Dry Stout', 'Export-Style Stout'],
      },
      {
        name: 'North American Origin Ale Styles',
        options: [
          'Golden or Blonde Ale',
          'Session India Pale Ale',
          'American-Style Amber/Red Ale',
          'American-Style Pale Ale',
          'Juicy or Hazy Pale Ale',
          'American-Style Strong Pale Ale',
          'Juicy or Hazy Strong Pale Ale',
          'American-Style India Pale Ale',
          'Juicy or Hazy India Pale Ale',
          'American-Belgo-Style Ale',
          'American-Style Brown Ale',
          'American-Style Black Ale',
          'American-Style Stout',
          'American-Style Imperial Porter',
          'American-Style Imperial Stout',
          'Double Hoppy Red Ale',
          'Imperial Red Ale',
          'American-Style Imperial or Double India Pale Ale',
          'Juicy or Hazy Imperial or Double India Pale Ale',
          'American-Style Barley Wine Ale',
          'American-Style Wheat Wine Ale',
          'Smoke Porter',
          'American-Style Sour Ale',
          'American-Style Fruited Sour Ale',
          'West Coast-Style India Pale Ale',
        ],
      },
      {
        name: 'German Origin Ale Styles',
        options: [
          'German-Style Koelsch',
          'German-Style Altbier',
          'Berliner-Style Weisse',
          'Leipzig-Style Gose',
          'Contemporary-Style Gose',
          'South German-Style Hefeweizen',
          'South German-Style Kristal Weizen',
          'German-Style Leichtes Weizen',
          'South German-Style Bernsteinfarbenes Weizen',
          'South German-Style Dunkel Weizen',
          'South German-Style Weizenbock',
          'German-Style Rye Ale',
          'Bamberg-Style Weiss Rauchbier',
          'Kellerbier or Zwickelbier',
        ],
      },
      {
        name: 'Belgian and French Origin Ale Styles',
        options: [
          'Belgian-Style Table Beer',
          'Belgian-Style Session Ale',
          'Belgian-Style Speciale Belge',
          'Belgian-Style Blonde Ale',
          'Belgian-Style Strong Blonde Ale',
          'Belgian-Style Strong Dark Ale',
          'Belgian-Style Dubbel',
          'Belgian-Style Tripel',
          'Belgian-Style Quadrupel',
          'Belgian-Style Witbier',
          'Classic French & Belgian-Style Saison',
          'Specialty Saison',
          'French-Style Bière de Garde',
          'Belgian-Style Flanders Oud Bruin or Oud Red Ale',
          'Belgian-Style Lambic',
          'Traditional Belgian-Style Gueuze',
          'Contemporary Belgian-Style Spontaneous Fermented Ale',
          'Belgian-Style Fruit Lambic',
          'Other Belgian-Style Ale',
        ],
      },
      {
        name: 'Other Origin Ale Styles',
        options: [
          'Grodziskie',
          'Adambier',
          'Dutch-Style Kuit, Kuyt or Koyt',
          'International-Style Pale Ale',
          'Classic Australian-Style Pale Ale',
          'Australian-Style Pale Ale',
          'New Zealand-Style Pale Ale',
          'New Zealand-Style India Pale Ale',
          'Finnish-Style Sahti',
          'Swedish-Style Gotlandsdricke',
          'Breslau-Style Schoeps',
        ],
      },
    ],
  },
  {
    category: 'Lager Styles',
    styles: [
      {
        name: 'European Origin Lager Styles',
        options: [
          'German-Style Leichtbier',
          'German-Style Pilsener',
          'Bohemian-Style Pilsener',
          'Munich-Style Helles',
          'Dortmunder/European-Style Export',
          'Vienna-Style Lager',
          'Franconian-Style Rotbier',
          'German-Style Maerzen',
          'German-Style Oktoberfest/Wiesn',
          'Munich-Style Dunkel',
          'European-Style Dark Lager',
          'German-Style Schwarzbier',
          'Bamberg-Style Helles Rauchbier',
          'Bamberg-Style Maerzen Rauchbier',
          'Bamberg-Style Bock Rauchbier',
          'German-Style Heller Bock/Maibock',
          'Traditional German-Style Bock',
          'German-Style Doppelbock',
          'German-Style Eisbock',
          'Chocolate or Cocoa Beer',
        ],
      },
      {
        name: 'North American Origin Lager Styles',
        options: [
          'American-Style Lager',
          'Contemporary American-Style Lager',
          'American-Style Light Lager',
          'Contemporary American-Style Light Lager',
          'American-Style Pilsener',
          'Contemporary American-Style Pilsener',
          'American-Style India Pale Lager',
          'American-Style Malt Liquor',
          'American-Style Amber Lager',
          'American-Style Maerzen/Oktoberfest',
          'American-Style Dark Lager',
        ],
      },
      {
        name: 'Other Origin Lager Styles',
        options: [
          'Australasian, Latin American or Tropical-Style Light Lager',
          'International-Style Pilsener',
          'Baltic-Style Porter',
        ],
      },
    ],
  },
  {
    category: 'Hybrid/Mixed Lagers or Ale',
    styles: [
      'Session Beer',
      'American-Style Cream Ale',
      'California Common Beer',
      'Kentucky Common Beer',
      'American-Style Wheat Beer',
      'American-Style Fruit Beer',
      'Fruit Wheat Beer',
      'Belgian-Style Fruit Beer',
      'Field Beer',
      'Pumpkin Spice Beer',
      'Pumpkin/Squash Beer',
      'Coffee Beer',
      'Chili Pepper Beer',
      'Herb and Spice Beer',
      'Specialty Beer',
      'Specialty Honey Beer',
      'Rye Beer',
      'Brett Beer',
      'Mixed-Culture Brett Beer',
      'Ginjo Beer or Sake-Yeast Beer',
      'Fresh Hop Beer',
      'Wood- and Barrel-Aged Sour Beer',
      'Aged Beer',
      'Experimental Beer',
      'Experimental India Pale Ale',
      'Historical Beer',
      'Wild Beer',
      'Smoke Beer',
      'Other Strong Ale or Lager',
      'Gluten-Free Beer',
      'Non-Alcohol Malt Beverage',
      'Dessert Stout or Pastry Stout',
    ],
  },
];